{% set version = "2.32.4.20260107" %}

package:
  name: types-requests
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/t/types-requests/types_requests-{{ version }}.tar.gz
  sha256: 018a11ac158f801bfa84857ddec1650750e393df8a004a8a9ae2a9bec6fcb24f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - urllib3 >=2

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
    - test -f $SP_DIR/requests-stubs/__init__.pyi  # [unix]

about:
  home: https://github.com/python/typeshed
  dev_url: https://github.com/python/typeshed
  summary: Typing stubs for requests
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
